# Generated by Django 5.0.6 on 2024-07-04 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(max_length=20, unique=True)),
                ('trip_type', models.CharField(choices=[('km', 'Kilometers'), ('hour', 'Hours')], default='km', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('fixed_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_km', models.PositiveIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('driver_name', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=50)),
                ('strt_km', models.PositiveIntegerField(blank=True, null=True)),
                ('end_km', models.PositiveIntegerField(blank=True, null=True)),
                ('strt_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('ride_hours', models.FloatField(blank=True, null=True)),
                ('ride_kms', models.FloatField(blank=True, null=True)),
                ('permit', models.FloatField(blank=True, null=True)),
                ('other_charge', models.FloatField(blank=True, null=True)),
                ('other_desc', models.TextField(blank=True, null=True)),
                ('strt_place', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('time_arrival', models.TimeField(null=True)),
                ('arrival_date', models.DateField(default=None, null=True)),
                ('trip_days', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('parking', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guidefee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('add_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tot_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripAdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
