# Generated by Django 5.0.6 on 2024-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='add_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='balance',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='extra_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fixed_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='guidefee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='toll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tot_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
