# Generated by Django 5.0.4 on 2024-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('fixed_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=100)),
                ('start_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_place', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('time_arrival', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('trip_days', models.IntegerField(blank=True, null=True)),
                ('tot_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
