# Generated by Django 5.0.4 on 2024-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('km', 'Kilometers'), ('hour', 'Hours')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
