# Generated by Django 5.0.4 on 2024-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trip_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
