# Generated by Django 5.0.6 on 2024-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trip_add_charges_alter_trip_advance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_hour',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_hour',
            new_name='ride_hours',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
