# Generated by Django 5.0.4 on 2024-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trip_date_alter_trip_extra_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='guest_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_km',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
