# Generated by Django 5.0.6 on 2024-06-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_end_hour_trip_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='start_km',
            new_name='strt_km',
        ),
    ]
