# Generated by Django 5.0.6 on 2024-06-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_start_km_trip_strt_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='start_time',
            new_name='strt_time',
        ),
    ]
