# Generated by Django 5.0.6 on 2024-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_start_time_trip_strt_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
